### PR TITLE
[HOLD] Workaround stderr bug rules_swift

### PR DESCRIPTION
**Pull request by jerrymarino**
Workaround for https://github.com/bazelbuild/rules_swift/issues/640

Fixes https://github.com/bazel-ios/rules_ios/issues/252

### CODE REVIEW

**Comment by jerrymarino** [comment]
For now I've created the tag `rules-ios/4.1.0` and reverted the 2 mentioned rules_swift issues that busted stderr in the worker

**Comment by jerrymarino** [comment]
Github flake?
```
Run bazelisk test --local_test_jobs=1 -- //... -//tests/ios/...
Starting local Bazel server and connecting to it...
... still trying to connect to local Bazel server after 10 seconds ...
... still trying to connect to local Bazel server after 20 seconds ...
... still trying to connect to local Bazel server after 30 seconds ...
... still trying to connect to local Bazel server after 40 seconds ...
... still trying to connect to local Bazel server after 50 seconds ...
... still trying to connect to local Bazel server after 60 seconds ...
... still trying to connect to local Bazel server after 70 seconds ...
... still trying to connect to local Bazel server after 80 seconds ...
... still trying to connect to local Bazel server after 90 seconds ...
... still trying to connect to local Bazel server after 100 seconds ...
... still trying to connect to local Bazel server after 110 seconds ...
FATAL: couldn't connect to server (1198) after 120 seconds.
Error: Process completed with exit code 37.
```

**Review by justinseanmartin — APPROVED** [review]

**Review by thiagohmcruz — APPROVED** [review]

**Comment by jerrymarino** [comment]
When I run:
```
bazel build -s tests/ios/app:SwiftLib --swiftcopt=-whole-module-optimization
```

I don't seem to get them 🤔  - maybe time for an integration test

**Comment by jerrymarino** [comment]
So it's probably a bug when using wmo

**Comment by jerrymarino** [comment]
It looks like the most recent commits on rules_swift seem to break rules_apple now 

Specifically https://github.com/bazel-ios/rules_swift/commit/7e284a9b8d622ada3a747f5e4f607b6f4a9d1402 and prior refactoring.

**Pull request merged**
