### PR TITLE
Bump rules_apple to pick up smartcard identities support

### PR DESCRIPTION
**Pull request by thiagohmcruz**
To pick up https://github.com/bazelbuild/rules_apple/pull/1181

### CODE REVIEW

**Comment by thiagohmcruz** [comment]
cc @jerrymarino 

```sh
ERROR: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_runner/c2342bca25695567c8c3f3be166b56b3/external/build_bazel_rules_apple/apple/internal/apple_framework_import.bzl", line 62, column 6, in <toplevel>
		"swift_clang_module_aspect",
Error: file '@build_bazel_rules_swift//swift:swift.bzl' does not contain symbol 'swift_clang_module_aspect'
```

**Comment by jerrymarino** [comment]
@thiagohmcruz Yep it looks like we'll need to rebase our rules_swift fork again. I've been thinking about simplifying the dependency altogether, but I think I've got a compromise that will let us drop the fork:  https://github.com/bazel-ios/rules_ios/pull/251 - Let's sync up offline about it

**Comment by jerrymarino** [comment]
@thiagohmcruz The rules_swift PR has landed this morning - so we can fix the issue you're hitting by rebasing rules_ios once https://github.com/bazel-ios/rules_ios/pull/246 lands

**Comment by thiagohmcruz** [comment]
> @thiagohmcruz The rules_swift PR has landed this morning - so we can fix the issue you're hitting by rebasing rules_ios once #246 lands

Awesome, thx @jerrymarino! That PR LGTM

**Review by segiddins — APPROVED** [review]

**Pull request merged**
