### PR TITLE
Pass data to swift_library when relevant

### PR DESCRIPTION
**Pull request by barbasevich**
Pass resources to swift_library when there are swift sources.
Otherwise, pass to objc_library.

[#74] Fixes Unknown class in Interface Builder file issue.

### CODE REVIEW

**Comment by barbasevich** [comment]
`rules_apple:74eca5857a136b9f1e2020886be76b791eb08231` could not be parsed.

Seems the ref should be updated.

**Comment by segiddins** [comment]
It would be nice to add a xib to one of the tests, so we can test `customModuleProvider="target"` indeed works

**Comment by barbasevich** [comment]
@segiddins Agree, added.

**Comment by segiddins** [comment]
Thanks!

**Pull request merged**
