### PR TITLE
Update bzlmod files for first publish

### PR DESCRIPTION
**Pull request by luispadron**
Feedback from: https://github.com/bazelbuild/bazel-central-registry/pull/1052

### CODE REVIEW

**Review by mattrobmattrob — APPROVED** [review]

**Review by fmeum — COMMENTED** [review]
This looks okay assuming that building everything doesn't require dev dependencies: They will not be available in the BCR test setup which works by creating a synthetic empty module depending on your root module - your module won't be the root module.

**Comment by luispadron** [comment]
> This looks okay assuming that building everything doesn't require dev dependencies: They will not be available in the BCR test setup which works by creating a synthetic empty module depending on your root module - your module won't be the root module.

Makes sense, so i'll make this more strict to just build `//rules` since some other things require dev dependencies.

**Review by thiagohmcruz — APPROVED** [review]

**Comment by luispadron** [comment]
Noticing some more changes I need to make to `MODULE.bazel`, testing with path override. Will update this PR.

**Comment by luispadron** [comment]
Had to make two changes:

- Mark `bazel_skylib` as a non-dev dependency, this is loaded by our rules so it cant be development only.
- Move the buildifier target from `//:BUILD.bazel` to `//tools:BUILD.bazel`, this allows us to move the load out of the rules path and allows us to keep buildifier as a dev depenedency
  - I added an `alias` so you can still do `bazel run //:buildifier`

With these changes, I get a green build depending on rules_ios from another bzlmod module:

```sh
bazel build @rules_ios//rules/...        
                                                                                                     
INFO: Analyzed 67 targets (134 packages loaded, 17858 targets configured).
INFO: Found 67 targets...
INFO: From Linking external/rules_ios~override/rules/hmap/hmaptest:
ld: warning: ignoring duplicate libraries: '-lc++'
INFO: From Linking external/rules_ios~override/rules/hmap/hmaptool:
ld: warning: ignoring duplicate libraries: '-lc++'
INFO: From Linking external/rules_ios~override/rules/hmap/hmapdump:
ld: warning: ignoring duplicate libraries: '-lc++'
INFO: Elapsed time: 28.322s, Critical Path: 7.12s
INFO: 442 processes: 257 internal, 142 darwin-sandbox, 43 local.
INFO: Build completed successfully, 442 total actions
```

**Pull request merged**
