### PR TITLE
[Bazel] [Xcode] Support running UI test without debugger

### PR DESCRIPTION
**Pull request by yongjincho92**

### CODE REVIEW

**Review by jerrymarino — APPROVED** [review]

**Comment by jerrymarino** [comment]
Thanks for the PR @yongjincho92 👍 . LGTM to get this done. Running these on device locally will need other changes as you may have found

**Comment by yongjincho92** [comment]
@jerrymarino all my machines are not able to run Xcode 12.5.1 anymore due to OS upgrades. https://github.com/bazel-ios/rules_ios/runs/7476273222?check_suite_focus=true says that the process exited with error code 1, however, it's hard to tell which part of the check it's failing. Running the test on my machine with Xcode 13 seems to have the exit code of 0 (checked with `echo $?` on different parts of the code). Do you have some insights what check the .xcodeproj test is failing? 

ccing @thiagohmcruz since he's working on xcodeproj actively as well.

**Comment by luispadron** [comment]
If we can get #511 then we could probably get around the Xcode 12 failures, that PR is blocked though and need some help resolving the existing failures

**Comment by luispadron** [comment]
@yongjincho92 Xcode 13.4.1 is now the minimum, you can rebase and give it another shot

**Comment by yongjincho92** [comment]
Was setting up git on my new machine and messed up the state. Will re-open later

**Comment by mattrobmattrob** [comment]
I'm going to need this in the near future. Anyone actively working on it?

**Pull request closed without merging**
