### PR TITLE
Point Xcode at LD stub

### LINKED ISSUE #228: [xcodeproj] project generator is building tests with Xcode
Hello! I've noticed that the Xcode project is building some tests with Xcode in my project. Is it expected to build the tests with Xcode or Bazel? cc @thiagohmcruz @amberdixon

### PR DESCRIPTION
**Pull request by jerrymarino**
When building a C++ file, setting LD in Xcode doesn't stub out the
linker, it's a different codepath.

This is a simple way to point at the stub by relying on a public clang
flag `-fuse-ld` Ideally we can replace the full build system without
stubbing out tools e.g. with something like XCBuildKit longer term.

Fixes #228

### CODE REVIEW

**Review by justinseanmartin — APPROVED** [review]

**Review by amberdixon — APPROVED** [review]
thanks Jerry!

**Review by thiagohmcruz — APPROVED** [review]

**Comment by keith** [comment]
Seems like we should report this to the apple folks too. Is there a LDCPP maybe?

**Comment by jerrymarino** [comment]
You've got it! I'm glad we found a quick fix for it 🥳 - longer term I'm curious to evaluate using XCHammer's [xcode_project rule](https://github.com/pinterest/xchammer#bazel-build-xcode-projects) as another easy way to fix it.

+1 to a feedback! I'd expect it to use `CXX`, as it runs `clang++` - I couldn't find docs or info about other linker build settings than `LD`

**Comment by jerrymarino** [comment]
It looks like the CI is now flaking on `Build and Test` - any suggestions on how to fix this - if it's just flaky today but the tests work locally will land and file an issue to investigate the CI problem.

**Comment by justinseanmartin** [comment]
> It looks like the CI is now flaking on `Build and Test` - any suggestions on how to fix this - if it's just flaky today but the tests work locally will land and file an issue to investigate the CI problem.

Looks like it passed on rerun. I don't know if there is a way to see the historical results, but without that there isn't enough context to know why it failed the first time.

**Comment by jerrymarino** [comment]
Maybe they can give us elastic search on the CI logs 🤔

**Comment by keith** [comment]
I filed FB9056166 about this

**Comment by keith** [comment]
turns out LDPLUSPLUS exists

**Pull request merged**
