### PR TITLE
Some fixes to the xcodeproj rule

### PR DESCRIPTION
**Pull request by acecilia**
Fix xcodeproj: 
* Pass a custom name correctly
* Add the host app to the project when adding the transitive dependencies (seems it was forgotten)

### CODE REVIEW

**Comment by segiddins** [comment]
cc @amberdixon / @gyfelton to review

Would you mind adding a test that covers the issues you're addressing? Thanks!

**Comment by acecilia** [comment]
Test added :)

**Comment by acecilia** [comment]
I would like to get you opinion on the following, if you guys dont mind :)

I see that the `xcodeproj` rule generates targets that build with bazel. I was thinking about tweaking the rule, so it is possible to also generate normal targets that run with `xcodebuild` (control it with a parameter). Either have one project with `MyTarget-bazel` and `MyTarget-xcodebuild`, or two projects `MyProject-bazel.xcodeproj` and `MyProject-xcodebuild.xcodeproj`. What I would like to do is to easily be able switch between bazel and xcodebuild. Seems like something that should be not so difficult to do. What do you think about this?

**Review by gyfelton — APPROVED** [review]
Thanks for covering this case! Yeah I think we generally lack of tests when include_transitive_targets = true, I have another issue to track a similar problem: https://github.com/bazel-ios/rules_ios/issues/106

**Comment by gyfelton** [comment]
> I would like to get you opinion on the following, if you guys dont mind :)
> 
> I see that the `xcodeproj` rule generates targets that build with bazel. I was thinking about tweaking the rule, so it is possible to also generate normal targets that run with `xcodebuild` (control it with a parameter). Either have one project with `MyTarget-bazel` and `MyTarget-xcodebuild`, or two projects `MyProject-bazel.xcodeproj` and `MyProject-xcodebuild.xcodeproj`. What I would like to do is to easily be able to switch between bazel and xcodebuild. Seems like something that shouldn't be so difficult to do. What do you think about this? Did you try something like this before?

I say that this should be inside a brand new rule that its only job is to generate a normal xcodeproj (via XcodeGen).

**Comment by acecilia** [comment]
> I say that this should be inside a brand new rule that its only job is to generate a normal xcodeproj (via XcodeGen).

I see, thanks :) In that case, how would you share code between the `xcodeproj-bazel` rule and the `xcodeproj-xcodebuild` rule? My initial thought was that both would be very similar

**Review by amberdixon — APPROVED** [review]
Thanks for addressing these issues!

**Comment by amberdixon** [comment]
> > I say that this should be inside a brand new rule that its only job is to generate a normal xcodeproj (via XcodeGen).
> 
> I see, thanks :) In that case, how would you share code between the `xcodeproj-bazel` rule and the `xcodeproj-xcodebuild` rule? My initial thought was that both would be very similar: since files, targets and dependencies are shared, seems like the only differences would be a bunch of build settings

This is a good idea, @gyfelton . As far as implementing it, I think it would be pretty simple, the xcodeproject could just contain targets and schemes that match the ones listed in the bazel project and with the same set of source files.

**Comment by gyfelton** [comment]
> > > I say that this should be inside a brand new rule that its only job is to generate a normal xcodeproj (via XcodeGen).
> > 
> > 
> > I see, thanks :) In that case, how would you share code between the `xcodeproj-bazel` rule and the `xcodeproj-xcodebuild` rule? My initial thought was that both would be very similar: since files, targets and dependencies are shared, seems like the only differences would be a bunch of build settings
> 
> This is a good idea, @gyfelton . As far as implementing it, I think it would be pretty simple, the xcodeproject could just contain targets and schemes that match the ones listed in the bazel project and with the same set of source files.

I worried more about the maintenances needed if sharing of code is done, specifically each time when we are adding a new build setting/changing behaviors, we have to verify the correctness on both sides. Nevertheless if this enforces a better separation of logics inside existing rule (what is for a normal project, and what is for bazel), I am definitely in favor of it.

**Comment by acecilia** [comment]
Is this ready to merge? :)

**Comment by gyfelton** [comment]
@acecilia go ahead!

**Comment by gyfelton** [comment]
@acecilia did not realize you cannot merge it, I merged. Thanks!

**Pull request merged**
