### PR TITLE
Add shardcount to ios_unit_test kwargs

### PR DESCRIPTION
**Pull request by dostrander**

### CODE REVIEW

**Review by segiddins — APPROVED** [review]

**Review by congt — APPROVED** [review]

**Comment by keith** [comment]
just curious if any iOS test runners support this?

**Comment by segiddins** [comment]
@keith we (@dostrander) is working on one right now 😉

**Comment by keith** [comment]
what's the thesis around time savings? curious about this vs having many test bundles (but maybe would be helpful for mono test bundles?)

**Comment by dostrander** [comment]
@keith I think having many test bundles would work and give you very similar results, however would put the onus on the individual module owner to divvy up those tests evenly as the module (and the test counts) grow

**Pull request merged**
