### PR TITLE
[Bazel6] Upgrade to Bazel 6.0.0

### PR DESCRIPTION
**Pull request by mattrobmattrob**
## Changes
- [Remove `--experimental_worker_allow_json_protocol`](https://github.com/bazel-ios/rules_ios/commit/2c80b95cf5d08b7e90f95db5522afad836ecbcc4) (https://github.com/bazel-ios/rules_ios/pull/615)
- [Handle removal of `ObjcProvider.direct_headers`](https://github.com/bazel-ios/rules_ios/commit/b9bc662dfa3e4eaf83f7842f4cf843a9db7ca20a) (https://github.com/bazel-ios/rules_ios/pull/620)
- [Manufacture empty `CcInfo` for `precompiled_apple_resource_bundle`](https://github.com/bazel-ios/rules_ios/pull/616/commits/991167a3ad1489bb0439d7cd2b6b0afa3b6ce994) (https://github.com/bazel-ios/rules_ios/pull/622)
- [Correct the symlink’d outputs from `_framework_packaging`](https://github.com/bazel-ios/rules_ios/pull/616/commits/45ded06b4a35823910243c760b1a90152d873199) (https://github.com/bazel-ios/rules_ios/pull/624)
- [Fix `header` not recognized key in `ObjcProvider`](https://github.com/bazel-ios/rules_ios/pull/616/commits/445678c1afb8f23bc487050a41c5493e65f860a3) (https://github.com/bazel-ios/rules_ios/pull/625)

### CODE REVIEW

**Comment by jerrymarino** [comment]
@mattrobmattrob awesome stuff 👏 !

**Comment by justinseanmartin** [comment]
After this change, CI will only validate against Bazel 6, right? If we're actively supporting Bazel 5 & Bazel 6, should we add a fork of the test configs that continues to run against Bazel 5?

**Comment by mattrobmattrob** [comment]
> After this change, CI will only validate against Bazel 6, right? If we're actively supporting Bazel 5 & Bazel 6, should we add a fork of the test configs that continues to run against Bazel 5?

For sure, @justinseanmartin. I wanted to have a conversation with you all to determine what we want to do. I'm okay _not_ merging this until we feel like "we support 6.0.0 and newer" is how we feel.

I'm hesitant to do much more in CI given those builds are already pretty slow/we're dealing with PR machine contention as it goes. But if you all are cool with it (you all are likely the majority of PR load at any time) then I'm happy to create a Bazel 6 test replication once it's officially released.

**Review by jerrymarino — APPROVED** [review]
This seems to pass basic smoke tests on our end BTW ❤️ . I think it's reasonable to bump this onto 6.0 on CI given the [worrysome 6.x.x changes](https://github.com/bazel-ios/rules_ios/pull/625) are backwards compatible to a 5.x.x release. Someone will have to vet it more in-depth I think 

The 6.0 release seems to be delayed but [is coming soon](https://github.com/bazelbuild/bazel/issues/16159) - does it seem reasonable to merge it when we can get `.bazelversion` onto `6.0.0`?

**Comment by mattrobmattrob** [comment]
> The 6.0 release seems to be delayed but [is coming soon](https://github.com/bazelbuild/bazel/issues/16159) - does it seem reasonable to merge it when we can get `.bazelversion` onto `6.0.0`?

Thanks for testing it, @jerrymarino!

My preference is to move `.bazelversion` to `6.0.0` if we can, yeah. If you all are okay with it, I can get this PR in good shape once the release blockers are solved and `6.0.0` exists. 👍

**Comment by jerrymarino** [comment]
@mattrobmattrob this looks awesome - and my understanding is we should be ready to land it.

Should we cut over to it 6.0 to celebrate [the release drop](https://github.com/bazelbuild/bazel/releases/tag/6.0.0) that just happened?

**Comment by mattrobmattrob** [comment]
I already did, @jerrymarino 😊

**Comment by mattrobmattrob** [comment]
> That's great to hear - thanks again for making this happen! 👏 Should we land this bump of the version/project transitions then?

I'm good with it if you all are. 👍

**Review by luispadron — APPROVED** [review]
🚀

**Comment by jerrymarino** [comment]
Yeah for sure 🚢 🎄!

**Pull request merged**
